###
POST http://192.168.2.106:8000/o/token/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=wh
&password=123456
&client_id=ROk5LpJhejtelxOFfawt2wC3NPNLR1eQ7Vd8YyqJ
&client_secret=aPOhTH40kihodnZdlWovdB55LUKmbVQ20tBdEy9mY76HltFFmcgHTUR2IOu4YgSm4qoBjCbyaPmo9w41uHSlx7PkfZuluxoer1JDe0wrgsSMjGsL3CjpzpXnJrxCCv1L

###
GET http://192.168.2.106:8000/gift/api/gift
Content-Type: application/json
Authorization: Bearer 8sKAwsoDYvtt5QzMgrOYBeOW6h0Wbz

{
    "shopId": 1
}

###
POST http://192.168.2.122:8000/o/token/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=car1
&password=car123456
&client_id=nfj51EOyLmWEwUCuJaYFX3RlPyqmn2VxEpu7cRjl
&client_secret=tk9FOe6KQWzeu3B6GHiywLOxadrsZ6P70u4ObSVnZULHmFCDj6cEkUxzofoDbNiEe2A6THnPSipl9wWJUwJ7AjrJJPFxFJAcBLbLakEuHklqdQxikU2PWiUhE33hh8PG

###
GET http://192.168.2.122:8000/gift/api/gift
Content-Type: application/json
Authorization: Bearer FZFclaS35GMjlJuzjPCCNqh5bShU6J

{
    "shopId": 1
}