### test request
POST http://192.168.2.106:8000/o/token/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=wh
&password=123456

### 
curl -X POST -d "grant_type=password&username=wh&password=123456" -u"xZqdQIJDx0QIWjsdRfftm4rUvYTPw2sOj78OENx0:VkxRbnBeNdcJxHTzBMQihN9fEgdaHjpG6L4bFS6boeP6YSnc9JqBviVSUbXBagNupEcEhgIziEYtxNZczCSc7ZAYT2w0zrL2Nbh9d5VnB6rJFSd4poBjWQJfyKhl5lgx" http://192.168.2.108:8000/o/token/

###
POST http://192.168.2.106:8000/user/api/login HTTP/1.1
Content-Type: application/json

username=wh&password=123456


###
POST http://192.168.2.106:8000/o/token/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=wh
&password=123456
&client_id=fCm866Asp3sRChdsE9HDYcfweqcuaJdMhrGtYtD6
&client_secret=Ekr8gMAMWKPZTpsAEoifZMDgpHvZp5DtriAl0rp37LMRTDYbPaFCet4ZUMa0TOOucQp06jJXOxhC3TusKPlZi36goSjrfqPmUVGbB4ffVosEJoPxUZpsOWLPxPGIiPkA



